In [3]:
import pandas as pd

xls = pd.ExcelFile("../data/raw/ethiopia_fi_unified_data.xlsx")
print("Sheet names:", xls.sheet_names)

refs = pd.read_excel("../data/raw/reference_codes.xlsx")
print("Reference codes shape:", refs.shape)
refs.head()

Sheet names: ['ethiopia_fi_unified_data', 'Impact_sheet']
Reference codes shape: (71, 4)

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All

In [4]:
data_df = pd.read_excel("../data/raw/ethiopia_fi_unified_data.xlsx", sheet_name="ethiopia_fi_unified_data")
impact_df = pd.read_excel("../data/raw/ethiopia_fi_unified_data.xlsx", sheet_name="Impact_sheet")

print("Main sheet shape:", data_df.shape)
print("Main sheet columns:", list(data_df.columns))
print()
print("Impact sheet shape:", impact_df.shape)
print("Impact sheet columns:", list(impact_df.columns))

Main sheet shape: (43, 34)
Main sheet columns: ['record_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

Impact sheet shape: (14, 35)
Impact sheet columns: ['record_id', 'parent_id', 'record_type', 'category', 'pillar', 'indicator', 'indicator_code', 'indicator_direction', 'value_numeric', 'value_text', 'value_type', 'unit', 'observation_date', 'period_start', 'period_end', 'fiscal_year', 'gender', 'location', 'region', 'source_name', 'source_type', 'source_url', 'confidence', 'related_indicator', 'relationship_type', 'impact_direction', 'impact_magnitude', 'impact_estimate', 'lag_months', 'evidence_basis', 'comparable_country', 'collected_by', 'collection_date', 'original_text', 'notes']

In [5]:
print("Reference codes columns:", list(refs.columns))
refs.head(10)

Reference codes columns: ['field', 'code', 'description', 'applies_to']

,field,code,description,applies_to
0,record_type,observation,Actual measured value from a source,All
1,record_type,event,Policy launch market event or milestone,All
2,record_type,impact_link,Relationship between event and indicator (link...,All
3,record_type,target,Policy target or official goal,All
4,record_type,baseline,Starting point for comparison,All
5,record_type,forecast,Predicted future value,All
6,category,product_launch,New product or service introduced,event
7,category,market_entry,New competitor enters market,event
8,category,market_exit,Competitor leaves market,event
9,category,policy,Government strategy or regulatory framework,event

In [6]:
combined_df = pd.concat([data_df, impact_df], ignore_index=True)
print("Combined shape:", combined_df.shape)

print("\nRecords by record_type:")
print(combined_df["record_type"].value_counts(dropna=False))

print("\nRecords by pillar:")
print(combined_df["pillar"].value_counts(dropna=False))

print("\nRecords by source_type:")
print(combined_df["source_type"].value_counts(dropna=False))

print("\nRecords by confidence:")
print(combined_df["confidence"].value_counts(dropna=False))

Combined shape: (57, 35)

Records by record_type:
record_type
observation    30
impact_link    14
event          10
target          3
Name: count, dtype: int64

Records by pillar:
pillar
ACCESS           20
USAGE            17
NaN              10
GENDER            6
AFFORDABILITY     4
Name: count, dtype: int64

Records by source_type:
source_type
operator      15
NaN           14
survey        10
regulator      7
research       4
policy         3
calculated     2
news           2
Name: count, dtype: int64

Records by confidence:
confidence
high      44
medium    13
Name: count, dtype: int64

In [7]:
print(combined_df["source_type"].value_counts(dropna=False).to_string())

source_type
operator      15
NaN           14
survey        10
regulator      7
research       4
policy         3
calculated     2
news           2

In [8]:
print("observation_date range:")
print(pd.to_datetime(combined_df["observation_date"], errors="coerce").min(), "to",
      pd.to_datetime(combined_df["observation_date"], errors="coerce").max())

print("\nperiod_start / period_end range:")
print(pd.to_datetime(combined_df["period_start"], errors="coerce").min(), "to",
      pd.to_datetime(combined_df["period_end"], errors="coerce").max())

print("\nfiscal_year values:")
print(combined_df["fiscal_year"].dropna().unique())

print("\nHow many rows actually have an observation_date?")
print(combined_df["observation_date"].notna().sum(), "out of", len(combined_df))

observation_date range:
2014-12-31 00:00:00 to 2030-12-31 00:00:00

period_start / period_end range:
2021-09-01 00:00:00 to 2025-07-07 00:00:00

fiscal_year values:
[2014 2017 2021 2024 'FY2022/23' 'FY2024/25' 2025 'FY2023/24' 2028 2030
 2022 2023 'FY2025/26']

How many rows actually have an observation_date?
57 out of 57

In [9]:
print("Unique indicator_code values and counts:")
print(combined_df["indicator_code"].value_counts(dropna=False).to_string())

print("\nFor each indicator_code, which record_types use it:")
print(combined_df.groupby("indicator_code")["record_type"].apply(lambda x: x.value_counts().to_dict()))

Unique indicator_code values and counts:
indicator_code
NaN                   14
ACC_OWNERSHIP          7
ACC_FAYDA              4
ACC_MM_ACCOUNT         2
ACC_4G_COV             2
USG_P2P_COUNT          2
GEN_GAP_ACC            2
GEN_MM_SHARE           2
ACC_MOBILE_PEN         1
USG_P2P_VALUE          1
USG_ATM_COUNT          1
USG_ATM_VALUE          1
USG_CROSSOVER          1
USG_TELEBIRR_USERS     1
USG_TELEBIRR_VALUE     1
USG_MPESA_USERS        1
USG_MPESA_ACTIVE       1
USG_ACTIVE_RATE        1
AFF_DATA_INCOME        1
GEN_GAP_MOBILE         1
EVT_TELEBIRR           1
EVT_SAFARICOM          1
EVT_MPESA              1
EVT_FAYDA              1
EVT_FX_REFORM          1
EVT_CROSSOVER          1
EVT_MPESA_INTEROP      1
EVT_ETHIOPAY           1
EVT_NFIS2              1
EVT_SAFCOM_PRICE       1

For each indicator_code, which record_types use it:
indicator_code
ACC_4G_COV          observation    2.0
                    target         NaN
                    event          NaN
ACC_FAYDA           observation    3.0
                    target         1.0
                                  ...
USG_TELEBIRR_USERS  target         NaN
                    event          NaN
USG_TELEBIRR_VALUE  observation    1.0
                    target         NaN
                    event          NaN
Name: record_type, Length: 87, dtype: float64

In [10]:
coverage = pd.crosstab(combined_df["indicator_code"], combined_df["record_type"])
print(coverage.to_string())

record_type         event  observation  target
indicator_code
ACC_4G_COV              0            2       0
ACC_FAYDA               0            3       1
ACC_MM_ACCOUNT          0            2       0
ACC_MOBILE_PEN          0            1       0
ACC_OWNERSHIP           0            6       1
AFF_DATA_INCOME         0            1       0
EVT_CROSSOVER           1            0       0
EVT_ETHIOPAY            1            0       0
EVT_FAYDA               1            0       0
EVT_FX_REFORM           1            0       0
EVT_MPESA               1            0       0
EVT_MPESA_INTEROP       1            0       0
EVT_NFIS2               1            0       0
EVT_SAFARICOM           1            0       0
EVT_SAFCOM_PRICE        1            0       0
EVT_TELEBIRR            1            0       0
GEN_GAP_ACC             0            2       0
GEN_GAP_MOBILE          0            1       0
GEN_MM_SHARE            0            1       1
USG_ACTIVE_RATE         0            1       0
USG_ATM_COUNT           0            1       0
USG_ATM_VALUE           0            1       0
USG_CROSSOVER           0            1       0
USG_MPESA_ACTIVE        0            1       0
USG_MPESA_USERS         0            1       0
USG_P2P_COUNT           0            2       0
USG_P2P_VALUE           0            1       0
USG_TELEBIRR_USERS      0            1       0
USG_TELEBIRR_VALUE      0            1       0

In [11]:
usage_rows = combined_df[combined_df["pillar"] == "USAGE"][
    ["record_id", "indicator", "indicator_code", "value_numeric", "observation_date", "confidence"]
]
print(usage_rows.to_string())

   record_id                                     indicator      indicator_code  value_numeric observation_date confidence
14  REC_0015                         P2P Transaction Count       USG_P2P_COUNT   4.970000e+07       2024-07-07       high
15  REC_0016                         P2P Transaction Count       USG_P2P_COUNT   1.283000e+08       2025-07-07       high
16  REC_0017                         P2P Transaction Value       USG_P2P_VALUE   5.777000e+11       2025-07-07       high
17  REC_0018                         ATM Transaction Count       USG_ATM_COUNT   1.193000e+08       2025-07-07       high
18  REC_0019                         ATM Transaction Value       USG_ATM_VALUE   1.561000e+11       2025-07-07       high
19  REC_0020                       P2P/ATM Crossover Ratio       USG_CROSSOVER   1.080000e+00       2025-07-07       high
20  REC_0021                     Telebirr Registered Users  USG_TELEBIRR_USERS   5.484000e+07       2025-06-30       high
21  REC_0022                    Telebirr Transaction Value  USG_TELEBIRR_VALUE   2.380000e+12       2025-06-30       high
22  REC_0023                       M-Pesa Registered Users     USG_MPESA_USERS   1.080000e+07       2024-12-31       high
23  REC_0024                    M-Pesa 90-Day Active Users    USG_MPESA_ACTIVE   7.100000e+06       2024-12-31       high
24  REC_0025                    Mobile Money Activity Rate     USG_ACTIVE_RATE   6.600000e+01       2024-12-31       high
44  IMP_0002             Telebirr effect on Telebirr Users                 NaN            NaN       2021-05-17       high
45  IMP_0003           Telebirr effect on P2P Transactions                 NaN   2.500000e+01       2021-05-17     medium
48  IMP_0006                 M-Pesa effect on M-Pesa Users                 NaN            NaN       2023-08-01       high
53  IMP_0011  M-Pesa Interop effect on M-Pesa Active Users                 NaN   1.500000e+01       2025-10-27     medium
54  IMP_0012            M-Pesa Interop effect on P2P Count                 NaN   1.000000e+01       2025-10-27     medium
55  IMP_0013                  EthioPay effect on P2P Count                 NaN   1.500000e+01       2025-12-18     medium

In [12]:
events = combined_df[combined_df["record_type"] == "event"][
    ["record_id", "indicator_code", "category", "observation_date", "source_name", "confidence"]
].sort_values("observation_date")
print(events.to_string())

   record_id     indicator_code        category observation_date    source_name confidence
33  EVT_0001       EVT_TELEBIRR  product_launch       2021-05-17  Ethio Telecom       high
41  EVT_0009          EVT_NFIS2          policy       2021-09-01            NBE       high
34  EVT_0002      EVT_SAFARICOM    market_entry       2022-08-01           News       high
35  EVT_0003          EVT_MPESA  product_launch       2023-08-01      Safaricom       high
36  EVT_0004          EVT_FAYDA  infrastructure       2024-01-01           NIDP       high
37  EVT_0005      EVT_FX_REFORM          policy       2024-07-29            NBE       high
38  EVT_0006      EVT_CROSSOVER       milestone       2024-10-01      EthSwitch       high
39  EVT_0007  EVT_MPESA_INTEROP     partnership       2025-10-27      EthSwitch       high
42  EVT_0010   EVT_SAFCOM_PRICE         pricing       2025-12-15           News       high
40  EVT_0008       EVT_ETHIOPAY  infrastructure       2025-12-18  NBE/EthSwitch       high

In [13]:
impacts = combined_df[combined_df["record_type"] == "impact_link"][
    ["record_id", "parent_id", "indicator", "related_indicator", "relationship_type",
     "impact_direction", "impact_magnitude", "impact_estimate", "lag_months",
     "evidence_basis", "comparable_country", "confidence"]
]
print(impacts.to_string())

   record_id parent_id                                          indicator   related_indicator relationship_type impact_direction impact_magnitude  impact_estimate  lag_months evidence_basis comparable_country confidence
43  IMP_0001  EVT_0001               Telebirr effect on Account Ownership       ACC_OWNERSHIP            direct         increase             high             15.0        12.0     literature              Kenya     medium
44  IMP_0002  EVT_0001                  Telebirr effect on Telebirr Users  USG_TELEBIRR_USERS            direct         increase             high              NaN         3.0      empirical                NaN       high
45  IMP_0003  EVT_0001                Telebirr effect on P2P Transactions       USG_P2P_COUNT            direct         increase             high             25.0         6.0      empirical                NaN     medium
46  IMP_0004  EVT_0002                    Safaricom effect on 4G Coverage          ACC_4G_COV            direct         increase           medium             15.0        12.0      empirical                NaN     medium
47  IMP_0005  EVT_0002             Safaricom effect on Data Affordability     AFF_DATA_INCOME          indirect         decrease           medium            -20.0        12.0     literature             Rwanda     medium
48  IMP_0006  EVT_0003                      M-Pesa effect on M-Pesa Users     USG_MPESA_USERS            direct         increase             high              NaN         3.0      empirical                NaN       high
49  IMP_0007  EVT_0003         M-Pesa effect on Mobile Money Account Rate      ACC_MM_ACCOUNT            direct         increase           medium              5.0         6.0    theoretical                NaN     medium
50  IMP_0008  EVT_0004                  Fayda effect on Account Ownership       ACC_OWNERSHIP          enabling         increase           medium             10.0        24.0     literature              India     medium
51  IMP_0009  EVT_0004                         Fayda effect on Gender Gap         GEN_GAP_ACC          indirect         decrease           medium             -5.0        24.0     literature              India     medium
52  IMP_0010  EVT_0005             FX Reform effect on Data Affordability     AFF_DATA_INCOME          indirect         increase             high             30.0         3.0      empirical                NaN       high
53  IMP_0011  EVT_0007       M-Pesa Interop effect on M-Pesa Active Users    USG_MPESA_ACTIVE            direct         increase           medium             15.0         3.0     literature           Tanzania     medium
54  IMP_0012  EVT_0007                 M-Pesa Interop effect on P2P Count       USG_P2P_COUNT            direct         increase           medium             10.0         3.0     literature           Tanzania     medium
55  IMP_0013  EVT_0008                       EthioPay effect on P2P Count       USG_P2P_COUNT          indirect         increase           medium             15.0         6.0     literature              India     medium
56  IMP_0014  EVT_0010  Safaricom Price Hike effect on Data Affordability     AFF_DATA_INCOME            direct         increase              low             10.0         1.0      empirical                NaN       high

In [14]:
acc = combined_df[combined_df["indicator_code"] == "ACC_OWNERSHIP"][
    ["record_id", "record_type", "value_numeric", "observation_date", "source_name", "confidence"]
].sort_values("observation_date")
print(acc.to_string())

print()
usg_summary = combined_df[combined_df["indicator_code"].str.startswith("USG_", na=False)][
    ["record_id", "indicator", "indicator_code", "value_numeric", "observation_date"]
].sort_values("observation_date")
print(usg_summary.to_string())

   record_id  record_type  value_numeric observation_date         source_name confidence
0   REC_0001  observation           22.0       2014-12-31  Global Findex 2014       high
1   REC_0002  observation           35.0       2017-12-31  Global Findex 2017       high
2   REC_0003  observation           46.0       2021-12-31  Global Findex 2021       high
3   REC_0004  observation           56.0       2021-12-31  Global Findex 2021       high
4   REC_0005  observation           36.0       2021-12-31  Global Findex 2021       high
5   REC_0006  observation           49.0       2024-11-29  Global Findex 2024       high
30  REC_0031       target           70.0       2025-12-31    NFIS-II Strategy       high

   record_id                   indicator      indicator_code  value_numeric observation_date
14  REC_0015       P2P Transaction Count       USG_P2P_COUNT   4.970000e+07       2024-07-07
22  REC_0023     M-Pesa Registered Users     USG_MPESA_USERS   1.080000e+07       2024-12-31
23  REC_0024  M-Pesa 90-Day Active Users    USG_MPESA_ACTIVE   7.100000e+06       2024-12-31
24  REC_0025  Mobile Money Activity Rate     USG_ACTIVE_RATE   6.600000e+01       2024-12-31
20  REC_0021   Telebirr Registered Users  USG_TELEBIRR_USERS   5.484000e+07       2025-06-30
21  REC_0022  Telebirr Transaction Value  USG_TELEBIRR_VALUE   2.380000e+12       2025-06-30
15  REC_0016       P2P Transaction Count       USG_P2P_COUNT   1.283000e+08       2025-07-07
16  REC_0017       P2P Transaction Value       USG_P2P_VALUE   5.777000e+11       2025-07-07
17  REC_0018       ATM Transaction Count       USG_ATM_COUNT   1.193000e+08       2025-07-07
18  REC_0019       ATM Transaction Value       USG_ATM_VALUE   1.561000e+11       2025-07-07
19  REC_0020     P2P/ATM Crossover Ratio       USG_CROSSOVER   1.080000e+00       2025-07-07

In [15]:
new_rows = pd.DataFrame([
    {
        "record_id": "REC_0058",
        "record_type": "observation",
        "category": None,
        "pillar": "USAGE",
        "indicator": "Telebirr Registered Users",
        "indicator_code": "USG_TELEBIRR_USERS",
        "value_numeric": 21800000,
        "observation_date": "2022-06-30",
        "source_name": "Ethio Telecom (via Wikipedia, FY2021/22 results)",
        "source_type": "operator",
        "source_url": "https://en.wikipedia.org/wiki/Ethio_Telecom",
        "original_text": "Frehiwot said 21.8 million users signed up with this service",
        "confidence": "medium",
        "collected_by": "Maria",
        "collection_date": "2026-07-19",
        "notes": "Fills Telebirr user gap between 2021 launch and 2025 data point; FY2021/22 close (~June 2022)",
    },
    {
        "record_id": "REC_0059",
        "record_type": "observation",
        "category": None,
        "pillar": "USAGE",
        "indicator": "Telebirr Registered Users",
        "indicator_code": "USG_TELEBIRR_USERS",
        "value_numeric": 34300000,
        "observation_date": "2023-06-30",
        "source_name": "Ethio Telecom 2022/23 Annual Business Performance Report",
        "source_type": "operator",
        "source_url": "https://www.ethiotelecom.et/ethio-telecom-2022-23-annual-business-performance/",
        "original_text": "telebirr has 34.3 Million subscribers with a total transaction value",
        "confidence": "high",
        "collected_by": "Maria",
        "collection_date": "2026-07-19",
        "notes": "Fills Telebirr user gap between 2021 launch and 2025 data point; FY2022/23 close (~June 2023)",
    },
])

combined_df = pd.concat([combined_df, new_rows], ignore_index=True)
print(combined_df.shape)

(59, 35)

In [16]:
new_row = pd.DataFrame([{
    "record_id": "REC_0060",
    "record_type": "observation",
    "category": None,
    "pillar": "USAGE",
    "indicator": "M-Pesa Registered Users",
    "indicator_code": "USG_MPESA_USERS",
    "value_numeric": 3100000,
    "observation_date": "2023-12-31",
    "source_name": "Safaricom Ethiopia (via Technext)",
    "source_type": "operator",
    "source_url": "https://technext24.com/2024/02/07/safaricoms-m-pesa-3-1-m-users-ethiopia/",
    "original_text": "Safaricom, has posted 3.1 million M-PESA customers since its launch",
    "confidence": "high",
    "collected_by": "Maria",
    "collection_date": "2026-07-19",
    "notes": "Fills gap between M-Pesa's Aug 2023 launch and the existing Dec 2024 (10.8M) data point",
}])

combined_df = pd.concat([combined_df, new_row], ignore_index=True)
print(combined_df.shape)

(60, 35)

In [17]:
print(combined_df[combined_df["indicator_code"] == "ACC_4G_COV"][
    ["record_id", "value_numeric", "observation_date", "source_name"]
].to_string())

  record_id  value_numeric     observation_date                source_name
8  REC_0009           37.5  2023-06-30 00:00:00  Ethio Telecom LEAD Report
9  REC_0010           70.8  2025-06-30 00:00:00  Ethio Telecom LEAD Report

In [18]:
new_row = pd.DataFrame([{
    "record_id": "REC_0061",
    "record_type": "observation",
    "category": None,
    "pillar": "ACCESS",
    "indicator": "4G Population Coverage",
    "indicator_code": "ACC_4G_COV",
    "value_numeric": 44,
    "observation_date": "2024-12-31",
    "source_name": "International Telecommunication Union (ITU), via Ecofin Agency",
    "source_type": "industry_report",
    "source_url": "https://www.ecofinagency.com/news-digital/0206-56088-ethiopias-incumbent-operator-extends-4g-coverage-to-52-new-cities",
    "original_text": "only 44% of the population had access to 4G coverage in 2024",
    "confidence": "medium",
    "collected_by": "Maria",
    "collection_date": "2026-07-19",
    "notes": "Fills gap between existing 2023 (37.5%, Ethio Telecom) and 2025 (70.8%) points; independent ITU source, useful for cross-validation vs operator-reported figures",
}])

combined_df = pd.concat([combined_df, new_row], ignore_index=True)
print(combined_df.shape)

(61, 35)

In [19]:
new_event = pd.DataFrame([{
    "record_id": "EVT_0011",
    "record_type": "event",
    "category": "policy",
    "pillar": None,
    "indicator": "Ethiopia Telecom Sector Liberalization",
    "indicator_code": "EVT_LIBERALIZATION",
    "value_numeric": None,
    "observation_date": "2021-05-01",
    "source_name": "IFC / World Bank PPP; African Business",
    "source_type": "regulatory_report",
    "source_url": "https://ppp.worldbank.org/zh-hans/node/9571",
    "original_text": "the country's first competitively tendered telecommunications license was awarded",
    "confidence": "high",
    "collected_by": "Maria",
    "collection_date": "2026-07-19",
    "notes": "Root regulatory event enabling Safaricom's entry and subsequent M-Pesa launch; pillar left blank per unbiased-event design, distinct from EVT_SAFARICOM (market entry, Aug 2022) and EVT_MPESA (product launch, Aug 2023)",
}])

combined_df = pd.concat([combined_df, new_event], ignore_index=True)
print(combined_df.shape)

(62, 35)

In [20]:
new_event2 = pd.DataFrame([{
    "record_id": "EVT_0012",
    "record_type": "event",
    "category": "policy",
    "pillar": None,
    "indicator": "NBE Payment Instrument Issuers Directive",
    "indicator_code": "EVT_PII_DIRECTIVE",
    "value_numeric": None,
    "observation_date": "2020-04-01",
    "source_name": "National Bank of Ethiopia / Digital Policy Alert",
    "source_type": "regulatory_report",
    "source_url": "https://digitalpolicyalert.org/event/25713-implemented-nbe-licensing-and-authorisation-of-payment-instrument-issuers-directive-no-onps012020",
    "original_text": "the National Bank of Ethiopia (NBE) issued the Licensing and Authorisation of Payment Instrument Issuers Directive",
    "confidence": "high",
    "collected_by": "Maria",
    "collection_date": "2026-07-19",
    "notes": "Regulatory foundation enabling non-bank mobile money issuers (Telebirr, later M-Pesa); earliest event in the dataset, predates Telebirr launch by ~13 months",
}])

combined_df = pd.concat([combined_df, new_event2], ignore_index=True)
print(combined_df.shape)

(63, 35)

In [21]:
combined_df.to_excel("../data/processed/ethiopia_fi_unified_data_enriched.xlsx", index=False)
print("Saved.")

Saved.